sudo: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

language: android

jdk:
  - oraclejdk8
  - oraclejdk7

android:
  components:
    - tools
    - tools # https://github.com/travis-ci/travis-ci/issues/6059
    - platform-tools
    - android-23
    - build-tools-23.0.3

before_script:
  - export TERM=dumb

script:
  - mvn -f AndroidAnnotations/pom.xml install -P travis
  - mvn -f examples/maven/pom.xml install
  - ./examples/gradle/gradlew assembleDebug --build-file examples/gradle/build.gradle

after_success:
  - if [[ $TRAVIS_REPO_SLUG == 'androidannotations/androidannotations' && $TRAVIS_BRANCH == 'develop' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_JDK_VERSION == 'oraclejdk7' ]]; then mvn -f AndroidAnnotations/pom.xml -DskipTests -Dquiet -s settings.xml deploy ; fi

notifications:
  webhooks:
    urls:
      secure: BOoKIc3qLKIx4efsNqg3Z6ErgBIF6xKKljozg5/GxaSPr9R58W/rOfyNJKtVpzfGlD0Z0e8psTb5FPGs/CNRprUJwCANGJ72FIc+NuEdO0+kLpvsvkl0yWJc5WHuOzqTTlsuPjfATB820AFTboIoV9tQ9wNhHB4vpyRqKPErdjg=
    on_success: change
    on_failure: always
    on_start: false
